site_name: SI-CE Integration
site_description: Python package for automated capillary electrophoresis with Agilent ChemStation
site_author: Richard Maršala
site_url: https://github.com/Xixaus/SI-CE

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/Xixaus/SI-CE
repo_name: SI-CE

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [.]
          options:
            show_source: false
            show_root_heading: true
            show_root_toc_entry: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            docstring_section_style: table
            merge_init_into_class: true
            separate_signature: true
            line_length: 80
            show_if_no_docstring: false
            annotations_path: brief
            members_order: source
            group_by_category: true
            show_category_heading: true
            show_submodules: false

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - ChemStation API:
      - Introduction: chemstation-api/introduction.md
      - File Protocol: chemstation-api/file-protocol.md
      - Basic Operations: chemstation-api/basic-operations.md
      - Methods & Sequences: chemstation-api/methods-sequences.md
      - Troubleshooting: chemstation-api/troubleshooting.md
  - SIA API:
      - Introduction: sia-api/sia_introduction.md
      - Core comunication: sia-api/core_communication.md
      - Syringe Controller: sia-api/syringe_control.md
      - Valve Selector: sia-api/valve_control.md
      - Workflows: sia-api/ce_workflows.md
  - Tutorials:
      - First Analysis: tutorials/first-analysis.md
      - Batch Processing: tutorials/batch-processing.md
      - SIA-CE Integration: tutorials/sia-ce-integration.md
      - ChemStation Macros: tutorials/chemstation-macros.md
  - API Reference:
      - ChemStation API:
          - Main API: api-reference/chemstation-api.md
          - CE Module: api-reference/chemstation-ce.md
          - Methods Module: api-reference/chemstation-methods.md
          - Sequence Module: api-reference/chemstation-sequence.md
          - System Module: api-reference/chemstation-system.md
          - Validation Module: api-reference/chemstation-validation.md
      - SIA API:
          - Syringe Controller: api-reference/sia-syringe.md
          - Valve Selector: api-reference/sia-valve.md
          - Workflows: api-reference/sia-workflows.md
          - Configuration: api-reference/sia-config.md
      - Core Components:
          - Communication: api-reference/core-communication.md
          - Exceptions: api-reference/exceptions.md
  - Apeendix:
      - FAQ: appendix/faq.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Xixaus
    # - icon: fontawesome/brands/python
    #   link: https://pypi.org/project/sia-ce/
